baseURL = "https://experimental-vegan.com/"
languageCode = "en-US"
title = "Experimental Vegan: Open Source Cooking"
theme = "bootstrap-bp-hugo-theme"
# googleAnalytics = "UA-123-45"
copyright = "Vincent Giles"
enableRobotsTXT = true
pygmentsCodeFences = true
canonifyurls = true
paginate = 5

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[permalinks]
    posts = "/:year/:month/:slug/"
    post = "/:year/:month/:slug/"
    pages = "/:slug/"
    page = "/:slug/"

#[Author]  
#  name = "Sebastian Pech"

[params]
  description = "This website is the front end for an open source vegan cooking project"
  #images = ["logo.jpg"]
  showPostSummary = true
  startPageColumns = true
  # customDateFormat = "02.01.2006"
