baseURL = "https://experimental-vegan.com/"
languageCode = "en-us"
title = "Experimental Vegan"
theme = "hugo-paper"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about exp-vegan"
    url = "/about/"
    weight = -110

  [[menu.main]]
    identifier = "contact"
    name = "get in touch/participate"
    url = "mailto:charles.maroux@gmail.com"
    weight = -100

  [[menu.main]]
    identifier = "source"
    name = "view recipe source"
    url = "https://github.com/vgiles/exp-vegan-site-src/tree/master/content/post"
    weight = -80

  [[menu.main]]
    identifier = "support"
    name = "support exp vegan"
    url = "https://paypal.me/vgcomposer"
    weight = -60